const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Plugins.NinePatch,
		C3.Plugins.Shape3D,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Audio.Cnds.IsSilent
	];
};
self.C3_JsPropNameTable = [
	{固体: 0},
	{six: 0},
	{プラットフォーム: 0},
	{画面スクロール: 0},
	{seven: 0},
	{回転: 0},
	{six2: 0},
	{キーボード: 0},
	{スプライト: 0},
	{弾丸: 0},
	{six3: 0},
	{sixsixsixsevensevenseven: 0},
	{fuck21: 0},
	{スプライト2: 0},
	{タッチ: 0},
	{スプライト3: 0},
	{アンカー: 0},
	{TouchA: 0},
	{TouchB: 0},
	{Touch3: 0},
	{スプライト4: 0},
	{hai: 0},
	{fu211: 0},
	{ball: 0},
	{"3Dの形状": 0},
	{btn2: 0},
	{btn: 0},
	{スプライト5: 0},
	{テキスト: 0},
	{音声: 0}
];

self.InstanceType = {
	six: class extends self.ISpriteInstance {},
	seven: class extends self.ISpriteInstance {},
	six2: class extends self.ISpriteInstance {},
	キーボード: class extends self.IInstance {},
	スプライト: class extends self.ISpriteInstance {},
	six3: class extends self.ISpriteInstance {},
	sixsixsixsevensevenseven: class extends self.ISpriteInstance {},
	fuck21: class extends self.ISpriteInstance {},
	スプライト2: class extends self.ISpriteInstance {},
	タッチ: class extends self.IInstance {},
	スプライト3: class extends self.ISpriteInstance {},
	TouchA: class extends self.ISpriteInstance {},
	TouchB: class extends self.ISpriteInstance {},
	Touch3: class extends self.ISpriteInstance {},
	スプライト4: class extends self.ISpriteInstance {},
	hai: class extends self.I9PatchInstance {},
	fu211: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	_3Dの形状: class extends self.I3DShapeInstance {},
	btn2: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {},
	スプライト5: class extends self.ISpriteInstance {},
	テキスト: class extends self.ITextInstance {},
	音声: class extends self.IInstance {}
}